+) Update linux build to run in docker container

diff --git a/.github/workflows/ci_linux.yml b/.github/workflows/ci_linux.yml
--- a/.github/workflows/ci_linux.yml
+++ b/.github/workflows/ci_linux.yml
@@ -21,9 +21,15 @@ on:
 
 jobs:
   build-binaries-unix:
-    name: Build unix lib
+    name: Build unix lib in container
     runs-on: ubuntu-latest
+    container:
+      image: ghcr.io/streamingdv/libplacebo-jni-debian10:latest
+      credentials:
+        username: ${{ github.actor }}
+        password: ${{ secrets.GITHUB_TOKEN }}
     env:
+      PATH: /root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       BUILD_LIBPLACEBO: ${{ github.event.inputs.build_libplacebo }}
       BUILD_SHADERC: ${{ github.event.inputs.build_shaderc }}
       BUILD_VULKAN_LOADER: ${{ github.event.inputs.build_vulkan }}
@@ -64,65 +70,21 @@ jobs:
           repository: 'mm2/Little-CMS'
           path: 'Little-CMS'
 
-      #- name: Install glslang dependencies
-      #  run: |
-      #    sudo apt-get update
-      #    sudo apt-get install -y cmake g++ python3 python-is-python3
-
-      #- name: Checkout glslang repository
-      #  uses: actions/checkout@v2
-      #  with:
-      #    repository: 'KhronosGroup/glslang'
-      #    path: 'glslang'
-      #    ref: '14.0.0'
-
-      #- name: Compile and install glslang
-      #  run: |
-      #    cd glslang
-      #    ./update_glslang_sources.py
-      #    cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_HLSL=ON -DENABLE_SPVREMAPPER=ON -DENABLE_OPT=ON -DBUILD_EXTERNAL=ON -DENABLE_RTTI=ON -DENABLE_EXCEPTIONS=ON
-      #    cmake --build build --config Release -- -j$(nproc)
-
-      #- name: Compress glslang directory
-      #  run: tar -czvf glslang-full.tar.gz -C glslang .
-
-      #- name: Upload glslang directory archive
-      #  uses: actions/upload-artifact@v2
-      #  with:
-      #    name: glslang-full-archive
-      #    path: glslang-full.tar.gz
-
       - name: Extract glslang package
         run: |
           unzip glslang-linux-x64_x86-release-14.0.0.zip -d ./glslang-package
 
       - name: Copy glslang headers to /usr/include/
         run: |
-          sudo cp -r ./glslang-package/glslang-release-14.0.0/include/glslang /usr/include/
+          cp -r ./glslang-package/glslang-release-14.0.0/include/glslang /usr/include/
 
       - name: Copy glslang libs to /usr/lib/x86_64-linux-gnu/
         run: |
-          sudo cp -r ./glslang-package/glslang-release-14.0.0/lib/x86_64-linux-gnu/* /usr/lib/x86_64-linux-gnu/
+          cp -r ./glslang-package/glslang-release-14.0.0/lib/x86_64-linux-gnu/* /usr/lib/x86_64-linux-gnu/
 
       - name: Copy pkgconfig files to /usr/lib/x86_64-linux-gnu/pkgconfig
         run: |
-          sudo cp ./glslang-package/glslang-release-14.0.0/pkgconfig/* /usr/lib/x86_64-linux-gnu/pkgconfig/
-
-      - name: Install dependencies
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y libavcodec-dev libavformat-dev libegl1-mesa-dev libsdl2-dev libxxhash-dev libvulkan-dev liblcms2-dev build-essential libx11-xcb-dev libxkbcommon-dev libwayland-dev libxrandr-dev cmake
-
-      - name: Install xbxc dependencies
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y libxcb1-dev libxcb-randr0-dev libxcb-keysyms1-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-xkb-dev
-
-      - name: Install Meson and Ninja
-        run: |
-          sudo apt-get install -y python3-pip
-          pip3 install --upgrade meson==1.3.0
-          pip3 install --upgrade ninja==1.11.1
+          cp ./glslang-package/glslang-release-14.0.0/pkgconfig/* /usr/lib/x86_64-linux-gnu/pkgconfig/
 
       - name: Build Little-CMS
         if: env.BUILD_LCMS2 == 'true'
@@ -137,7 +99,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: lcms2-linux-x64bit
-          path: ${{github.workspace}}/Little-CMS
+          path: ${{ github.workspace }}/Little-CMS
 
       - name: Build shaderc
         if: env.BUILD_SHADERC == 'true'
@@ -153,8 +115,8 @@ jobs:
         if: env.BUILD_SHADERC == 'true'
         uses: actions/upload-artifact@v4
         with:
-          name: shaderc-artefacts-${{ matrix.arch }}
-          path: ${{github.workspace}}/shaderc
+          name: shaderc-artefacts-x64
+          path: ${{ github.workspace }}/shaderc
 
       - name: Build vulkan-loader
         if: env.BUILD_VULKAN_LOADER == 'true'
@@ -168,19 +130,36 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: vulkan-loader-artefacts-x64
-          path: ${{github.workspace}}/vulkan-loader
+          path: ${{ github.workspace }}/vulkan-loader
+
+      - name: Debug Confirm meson and ninja versions
+        run: |
+          which meson || echo "meson not found"
+          meson --version || echo "meson failed"
+          which ninja || echo "ninja not found"
+          ninja --version || echo "ninja failed"
+
+      - name: Debug Check pkg-config xxhash
+        run: pkg-config --exists libxxhash && echo "Found xxhash" || echo "Missing xxhash"
 
       - name: Apply fix_reuse_swapchain patch to libplacebo
         #if: env.BUILD_LIBPLACEBO == 'true'
         working-directory: ./libplacebo-jni-native/3rdparty/libplacebo
-        run: |
-          git apply ../fix_reuse_swapchain.patch
+        run: git apply ../fix_reuse_swapchain.patch
 
       - name: Apply vulkan use 16 bit for p010 to libplacebo
         #if: env.BUILD_LIBPLACEBO == 'true'
         working-directory: ./libplacebo-jni-native/3rdparty/libplacebo
+        run: git apply ../vulkan_use_16bit_for_p010.patch
+
+      - name: Remove problematic <version> include from common.h
+        working-directory: ./libplacebo-jni-native/3rdparty/libplacebo
         run: |
-          git apply ../vulkan_use_16bit_for_p010.patch
+          sed -i '/#include <version>/d' src/common.h
+
+      - name: Verify common.h patch
+        working-directory: ./libplacebo-jni-native/3rdparty/libplacebo
+        run: grep version src/common.h || echo "<version> successfully removed"
 
       - name: Build libplacebo
         #if: env.BUILD_LIBPLACEBO == 'true'
@@ -195,15 +174,13 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: libplacebo-artefacts-x64
-          path: ${{github.workspace}}/libplacebo-jni-native/3rdparty/libplacebo/install
+          path: ${{ github.workspace }}/libplacebo-jni-native/3rdparty/libplacebo/install
 
       - name: Make gradlew executable
         run: chmod +x ./gradlew
 
       - name: Install jq
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y jq
+        run: apt-get update && apt-get install -y jq
 
       - name: Build libplacebo-jni-java compile java
         run: |
@@ -212,34 +189,36 @@ jobs:
 
       - name: Configure and Build libplacebo-jni with CMake
         run: |
-          
-          LIBPLACEBO_LIB_PATH=${{github.workspace}}/libplacebo-jni-native/3rdparty/libplacebo/install/lib/x86_64-linux-gnu/libplacebo.a
-          LIBPLACEBO_HEADERS_DIR=${{github.workspace}}/libplacebo-jni-native/3rdparty/libplacebo/install/include
-          
+          FULL_REPO_PATH="/__w/libplacebo-jni/libplacebo-jni"
+          LIBPLACEBO_LIB_PATH=${FULL_REPO_PATH}/libplacebo-jni-native/3rdparty/libplacebo/install/lib/x86_64-linux-gnu/libplacebo.a
+          LIBPLACEBO_HEADERS_DIR=${FULL_REPO_PATH}/libplacebo-jni-native/3rdparty/libplacebo/install/include
+
           cmake -G "Ninja" -B build -S ./libplacebo-jni-native \
             -DCMAKE_BUILD_TYPE=Release \
-            -DVULKAN_LIB_DIR=${{github.workspace}}/libs/vulkan-loader/linux/x64 \
-            -DLIBPLACEBO_LIB_PATH=${LIBPLACEBO_LIB_PATH} \
-            -DLIBPLACEBO_HEADERS_DIR=${LIBPLACEBO_HEADERS_DIR} \
-            -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{ github.workspace }}/build/nativeBinaries \
-            -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=${{ github.workspace }}/build/nativeBinaries \
-            -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=${{ github.workspace }}/build/nativeBinaries \
-            -DGENERATED_JNI_HEADERS_DIR=${{ github.workspace }}/build/generatedHeaders \
-            -DSHADERC_LIB_DIR=${{github.workspace}}/libs/shaderc/linux/x64/lib \
-            -DSHADERC_HEADERS_DIR=${{github.workspace}}/libs/shaderc/linux/x64/include \
-            -DFFMPEG_DIR=${{github.workspace}}/libs/ffmpeg/linux/x64 \
-            -DLCMS2_DIR=${{github.workspace}}/libs/lcms2/linux/x64 \
-            -DNUKLEAR_DIR=${{github.workspace}}/Nuklear \
-            -DVKMEMALLOC_HEADERS=${{github.workspace}}/libs/vulkan-memory-allocator/include \
+            -DVULKAN_LIB_DIR="${FULL_REPO_PATH}/libs/vulkan-loader/linux/x64" \
+            -DLIBPLACEBO_LIB_PATH="${LIBPLACEBO_LIB_PATH}" \
+            -DLIBPLACEBO_HEADERS_DIR="${LIBPLACEBO_HEADERS_DIR}" \
+            -DCMAKE_RUNTIME_OUTPUT_DIRECTORY="${FULL_REPO_PATH}/build/nativeBinaries" \
+            -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="${FULL_REPO_PATH}/build/nativeBinaries" \
+            -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY="${FULL_REPO_PATH}/build/nativeBinaries" \
+            -DGENERATED_JNI_HEADERS_DIR="${FULL_REPO_PATH}/build/generatedHeaders" \
+            -DSHADERC_LIB_DIR="${FULL_REPO_PATH}/libs/shaderc/linux/x64/lib" \
+            -DSHADERC_HEADERS_DIR="${FULL_REPO_PATH}/libs/shaderc/linux/x64/include" \
+            -DFFMPEG_DIR="${FULL_REPO_PATH}/libs/ffmpeg/linux/x64" \
+            -DLCMS2_DIR="${FULL_REPO_PATH}/libs/lcms2/linux/x64" \
+            -DNUKLEAR_DIR="${FULL_REPO_PATH}/Nuklear" \
+            -DVKMEMALLOC_HEADERS="${FULL_REPO_PATH}/libs/vulkan-memory-allocator/include" \
             -DIS_RUNNING_ON_WINDOWS=OFF
+
           cmake --build build
-        shell: bash
 
       - name: Rename DLL file
-        run: mv ${{github.workspace}}/build/nativeBinaries/libplacebo-jni-native.so ${{github.workspace}}/build/nativeBinaries/libplacebo-jni-native-64.so
+        run: |
+          cp /__w/libplacebo-jni/libplacebo-jni/build/nativeBinaries/libplacebo-jni-native.so \
+             /__w/libplacebo-jni/libplacebo-jni/libplacebo-jni-native-64.so
 
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
         with:
           name: linux-libplacebo-jni-artifact-64bit
-          path: ${{github.workspace}}/build/nativeBinaries/libplacebo-jni-native-64.so
+          path: /__w/libplacebo-jni/libplacebo-jni/libplacebo-jni-native-64.so
