+) Update ci_windows.yml

diff --git a/.github/workflows/ci_windows.yml b/.github/workflows/ci_windows.yml
--- a/.github/workflows/ci_windows.yml
+++ b/.github/workflows/ci_windows.yml
@@ -168,22 +168,22 @@ jobs:
           name: libplacebo-artefacts-${{ matrix.arch }}
           path: ${{github.workspace}}/libplacebo-jni-native/3rdparty/libplacebo/install
 
-      - name: Download shaderc release Asset
-        run: |
-          browser_download_url=$(curl "https://api.github.com/repos/streamingdv/shaderc_combined/releases/tags/shaderc_combined_v1.0" | jq -r '.assets[] | select(.name == "shaderc_combined.zip") | .browser_download_url')
-          if [ -z "$browser_download_url" ]; then
-            echo "Error: Browser download URL not found."
-            exit 1
-          fi
-          curl -L -o shaderc_combined.zip "$browser_download_url"
-          ls -l shaderc_combined.zip
-          file shaderc_combined.zip
-        shell: msys2 {0}
+      #- name: Download shaderc release Asset
+      #  run: |
+      #    browser_download_url=$(curl "https://api.github.com/repos/streamingdv/shaderc_combined/releases/tags/shaderc_combined_v1.0" | jq -r '.assets[] | select(.name == "shaderc_combined.zip") | .browser_download_url')
+      #    if [ -z "$browser_download_url" ]; then
+      #      echo "Error: Browser download URL not found."
+      #      exit 1
+      #    fi
+      #    curl -L -o shaderc_combined.zip "$browser_download_url"
+      #    ls -l shaderc_combined.zip
+      #    file shaderc_combined.zip
+      #  shell: msys2 {0}
 
-      - name: Extract shaderc zip File
-        run: |
-          unzip shaderc_combined.zip -d ./
-        shell: msys2 {0}
+      #- name: Extract shaderc zip File
+      #  run: |
+      #    unzip shaderc_combined.zip -d ./
+      #  shell: msys2 {0}
 
       - name: Build libplacebo-jni-java compile java
         run: |
